// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

/// @title ErebusCodec
/// @notice Strict decoder and digest library for the canonical Erebus agreement encoding.
/// @dev The Rust implementation in `sdk/core` is normative; this library must reproduce its
///      bytes exactly. The known-answer test `test/ErebusVectors.t.sol` pins the decoder and the
///      three digests against vectors generated by the Rust core. A decoder that disagrees by one
///      byte produces a different commitment and every settlement fails, which is the intended,
///      loud failure mode.
///
///      Encoding rules: integers are big-endian at fixed width; variable byte strings and text
///      carry a `u16` length prefix; optional fields carry a `u8` presence tag; a decoder rejects
///      truncation, trailing bytes, unknown tags, out-of-range lengths, and invalid values.
library ErebusCodec {
    /// A canonical byte sequence could not be read, or a decoded value was invalid.
    error DecodeError(string reason);

    /// Domain separation for the agreement commitment (matches `commitment.rs`).
    bytes internal constant COMMITMENT_DOMAIN = "EREBUS_DEAL_COMMITMENT_V1";
    /// Domain separation for authorization digests (matches `auth.rs`).
    bytes internal constant AUTHORIZATION_DOMAIN = "EREBUS_DEAL_AUTHORIZATION_V1";
    /// Domain separation for the consumed deal identity (matches `commitment.rs`).
    bytes internal constant DEAL_NULLIFIER_DOMAIN = "EREBUS_DEAL_NULLIFIER_V1";

    /// Role tag for buyer authorizations.
    uint8 internal constant ROLE_BUYER = 1;
    /// Role tag for seller authorizations.
    uint8 internal constant ROLE_SELLER = 2;

    /// Bit for the `hidden-amount` guarantee; contradictory with public-bound settlement.
    uint32 internal constant GUARANTEE_HIDDEN_AMOUNT = 0x1;
    /// Bit for the `hidden-recipient` guarantee; contradictory with public-bound settlement.
    uint32 internal constant GUARANTEE_HIDDEN_RECIPIENT = 0x2;
    /// The guarantee this public-bound contract actually enforces.
    uint32 internal constant GUARANTEE_AGREEMENT_BOUND_SETTLEMENT = 0x4;
    /// Every guarantee bit this protocol version defines.
    uint32 internal constant GUARANTEE_KNOWN_BITS = 0xF;

    /// The one protocol version this encoder decodes.
    uint16 internal constant PROTOCOL_VERSION = 1;
    /// The one agreement suite this encoder decodes.
    uint16 internal constant SUITE_ID = 1;
    /// The public-bound settlement mode tag.
    uint8 internal constant MODE_PUBLIC_BOUND = 1;

    struct Cursor {
        bytes data;
        uint256 position;
    }

    struct Domain {
        string namespace;
        address settlementContract;
        bool hasSettlementContract;
        bool hasPool;
        uint32 verifierVersion;
    }

    /// Every terms field the settlement contract needs, plus the byte range of the domain.
    struct Terms {
        uint16 protocolVersion;
        uint16 suiteId;
        uint256 domainStart;
        uint256 domainEnd;
        string namespace;
        address settlementContract;
        bool hasSettlementContract;
        bool hasPool;
        uint32 verifierVersion;
        bytes32 dealId;
        uint32 revision;
        bytes32 transcriptRoot;
        address buyer;
        address seller;
        address paymentRecipient;
        string asset;
        uint128 amount;
        uint64 expiry;
        uint128 fee;
        address feeRecipient;
        bool hasFeeRecipient;
        uint8 settlementMode;
        uint32 requiredGuarantees;
        bytes32 settlementNonce;
    }

    // ---------------------------------------------------------------------
    // Decoding
    // ---------------------------------------------------------------------

    /// Decodes and validates a complete terms value.
    function decode(bytes memory data) internal pure returns (Terms memory terms) {
        Cursor memory cursor = Cursor(data, 0);
        terms.protocolVersion = readU16(cursor);
        terms.suiteId = readU16(cursor);

        terms.domainStart = cursor.position;
        Domain memory domain = readDomain(cursor);
        terms.domainEnd = cursor.position;
        terms.namespace = domain.namespace;
        terms.settlementContract = domain.settlementContract;
        terms.hasSettlementContract = domain.hasSettlementContract;
        terms.hasPool = domain.hasPool;
        terms.verifierVersion = domain.verifierVersion;

        terms.dealId = readRawBytes32(cursor, 16);
        terms.revision = readU32(cursor);
        terms.transcriptRoot = readBytes32(cursor);
        terms.buyer = readAddress(cursor);
        terms.seller = readAddress(cursor);
        terms.paymentRecipient = readAddress(cursor);
        terms.asset = readText(cursor, 1, 256);
        terms.amount = readU128(cursor);
        terms.expiry = readU64(cursor);
        terms.fee = readU128(cursor);
        terms.hasFeeRecipient = readPresence(cursor);
        if (terms.hasFeeRecipient) {
            terms.feeRecipient = readAddress(cursor);
        }
        terms.settlementMode = readU8(cursor);
        terms.requiredGuarantees = readU32(cursor);
        terms.settlementNonce = readBytes32(cursor);
        readService(cursor);

        if (cursor.position != data.length) {
            revert DecodeError("trailing bytes");
        }
        validate(terms);
    }

    function readDomain(Cursor memory cursor) private pure returns (Domain memory domain) {
        domain.namespace = readText(cursor, 5, 41);
        domain.hasSettlementContract = readPresence(cursor);
        if (domain.hasSettlementContract) {
            domain.settlementContract = readAddress(cursor);
        }
        domain.hasPool = readPresence(cursor);
        if (domain.hasPool) {
            readBytesField(cursor, 1, 64);
        }
        domain.verifierVersion = readU32(cursor);
    }

    /// Reads the service record and checks its own rules. The settlement contract does not use
    /// the service fields, but a decoder that skips them would not notice a malformed tail.
    function readService(Cursor memory cursor) private pure {
        readText(cursor, 1, 256); // resource
        uint128 quantity = readU128(cursor);
        readText(cursor, 1, 32); // unit
        readBytesField(cursor, 1, 64); // access recipient
        uint64 deadline = readU64(cursor);
        readText(cursor, 1, 64); // fulfillment method
        readFixed(cursor, 32); // fulfillment digest
        if (quantity == 0) {
            revert DecodeError("zero quantity");
        }
        if (deadline == 0) {
            revert DecodeError("zero delivery deadline");
        }
    }

    function validate(Terms memory terms) private pure {
        if (terms.protocolVersion != PROTOCOL_VERSION) {
            revert DecodeError("protocol version");
        }
        if (terms.suiteId != SUITE_ID) {
            revert DecodeError("suite id");
        }
        if (terms.settlementMode != MODE_PUBLIC_BOUND) {
            revert DecodeError("settlement mode");
        }
        if (terms.revision == 0) {
            revert DecodeError("zero revision");
        }
        if (terms.amount == 0) {
            revert DecodeError("zero amount");
        }
        if (terms.expiry == 0) {
            revert DecodeError("zero expiry");
        }
        if (
            terms.requiredGuarantees & ~GUARANTEE_KNOWN_BITS != 0
                || terms.requiredGuarantees & ~GUARANTEE_AGREEMENT_BOUND_SETTLEMENT != 0
        ) {
            revert DecodeError("guarantees");
        }
        if (terms.buyer == address(0) || terms.seller == address(0) || terms.paymentRecipient == address(0)) {
            revert DecodeError("zero address");
        }
        if (terms.hasFeeRecipient != (terms.fee != 0)) {
            revert DecodeError("fee recipient presence");
        }
        if (!terms.hasSettlementContract || terms.settlementContract == address(0)) {
            revert DecodeError("missing settlement contract");
        }
    }

    // ---------------------------------------------------------------------
    // Digests
    // ---------------------------------------------------------------------

    /// `keccak256("EREBUS_DEAL_COMMITMENT_V1" || terms || blinding)`.
    function commitment(bytes memory terms, bytes32 blinding) internal pure returns (bytes32) {
        return keccak256(abi.encodePacked(COMMITMENT_DOMAIN, terms, blinding));
    }

    /// `keccak256("EREBUS_DEAL_AUTHORIZATION_V1" || domain || role_tag || commitment)`.
    function authorizationDigest(bytes memory domain, uint8 roleTag, bytes32 dealCommitment)
        internal
        pure
        returns (bytes32)
    {
        return keccak256(abi.encodePacked(AUTHORIZATION_DOMAIN, domain, roleTag, dealCommitment));
    }

    /// `keccak256("EREBUS_DEAL_NULLIFIER_V1" || domain || buyer_key || settlement_nonce)`.
    function dealNullifier(bytes memory domain, address buyer, bytes32 settlementNonce)
        internal
        pure
        returns (bytes32)
    {
        return keccak256(abi.encodePacked(DEAL_NULLIFIER_DOMAIN, domain, buyer, settlementNonce));
    }

    /// The exact canonical bytes of the domain, sliced out of the terms encoding.
    function domainSlice(bytes memory terms, Terms memory decoded) internal pure returns (bytes memory out) {
        uint256 length = decoded.domainEnd - decoded.domainStart;
        out = new bytes(length);
        uint256 start = decoded.domainStart;
        for (uint256 i = 0; i < length; ++i) {
            out[i] = terms[start + i];
        }
    }

    // ---------------------------------------------------------------------
    // Token identifier
    // ---------------------------------------------------------------------

    /// Parses the ERC-20 address out of a CAIP-19 identifier of the form
    /// `eip155:<chainId>/erc20:0x<40 lowercase hex>`, requiring the namespace to equal the
    /// configured chain namespace. Uppercase hex and any other asset namespace are rejected: a
    /// silently aliased token address is exactly the kind of ambiguity this protocol forbids.
    function parseAssetToken(string memory asset, string memory expectedNamespace) internal pure returns (address) {
        bytes memory encoded = bytes(asset);
        bytes memory namespace = bytes(expectedNamespace);
        bytes memory suffix = bytes("/erc20:0x");
        if (encoded.length != namespace.length + suffix.length + 40) {
            revert DecodeError("asset identifier length");
        }
        for (uint256 i = 0; i < namespace.length; ++i) {
            if (encoded[i] != namespace[i]) {
                revert DecodeError("asset chain namespace");
            }
        }
        for (uint256 i = 0; i < suffix.length; ++i) {
            if (encoded[namespace.length + i] != suffix[i]) {
                revert DecodeError("asset namespace");
            }
        }
        uint160 parsed;
        uint256 digits = namespace.length + suffix.length;
        for (uint256 i = 0; i < 40; ++i) {
            parsed = (parsed << 4) | uint160(hexNibble(encoded[digits + i]));
        }
        return address(parsed);
    }

    function hexNibble(bytes1 character) private pure returns (uint8) {
        uint8 value = uint8(character);
        if (value >= 0x30 && value <= 0x39) {
            return value - 0x30;
        }
        if (value >= 0x61 && value <= 0x66) {
            return value - 0x57;
        }
        revert DecodeError("non-lowercase-hex asset reference");
    }

    // ---------------------------------------------------------------------
    // Primitive readers
    // ---------------------------------------------------------------------

    function remaining(Cursor memory cursor) private pure returns (uint256) {
        return cursor.data.length - cursor.position;
    }

    function take(Cursor memory cursor, uint256 length) private pure returns (bytes memory out) {
        if (length > remaining(cursor)) {
            revert DecodeError("truncated");
        }
        out = new bytes(length);
        uint256 start = cursor.position;
        for (uint256 i = 0; i < length; ++i) {
            out[i] = cursor.data[start + i];
        }
        cursor.position = start + length;
    }

    function readFixed(Cursor memory cursor, uint256 length) private pure returns (bytes memory) {
        return take(cursor, length);
    }

    function readU8(Cursor memory cursor) private pure returns (uint8 value) {
        bytes memory encoded = take(cursor, 1);
        value = uint8(encoded[0]);
    }

    function readU16(Cursor memory cursor) private pure returns (uint16 value) {
        bytes memory encoded = take(cursor, 2);
        value = (uint16(uint8(encoded[0])) << 8) | uint16(uint8(encoded[1]));
    }

    function readU32(Cursor memory cursor) private pure returns (uint32 value) {
        bytes memory encoded = take(cursor, 4);
        for (uint256 i = 0; i < 4; ++i) {
            value = (value << 8) | uint32(uint8(encoded[i]));
        }
    }

    function readU64(Cursor memory cursor) private pure returns (uint64 value) {
        bytes memory encoded = take(cursor, 8);
        for (uint256 i = 0; i < 8; ++i) {
            value = (value << 8) | uint64(uint8(encoded[i]));
        }
    }

    function readU128(Cursor memory cursor) private pure returns (uint128 value) {
        bytes memory encoded = take(cursor, 16);
        for (uint256 i = 0; i < 16; ++i) {
            value = (value << 8) | uint128(uint8(encoded[i]));
        }
    }

    function readBytes32(Cursor memory cursor) private pure returns (bytes32 value) {
        return readRawBytes32(cursor, 32);
    }

    /// Reads `length` raw bytes (no length prefix) right-aligned into a `bytes32`.
    function readRawBytes32(Cursor memory cursor, uint256 length) private pure returns (bytes32 value) {
        bytes memory encoded = take(cursor, length);
        for (uint256 i = 0; i < length; ++i) {
            value = (value << 8) | bytes32(uint256(uint8(encoded[i])));
        }
    }

    function readAddress(Cursor memory cursor) private pure returns (address value) {
        bytes memory encoded = readBytesField(cursor, 1, 64);
        if (encoded.length != 20) {
            revert DecodeError("address length");
        }
        uint160 parsed;
        for (uint256 i = 0; i < 20; ++i) {
            parsed = (parsed << 8) | uint160(uint8(encoded[i]));
        }
        return address(parsed);
    }

    function readBytesField(Cursor memory cursor, uint256 min, uint256 max) private pure returns (bytes memory value) {
        uint256 length = readU16(cursor);
        if (length < min || length > max) {
            revert DecodeError("length out of range");
        }
        value = take(cursor, length);
    }

    function readText(Cursor memory cursor, uint256 min, uint256 max) private pure returns (string memory value) {
        bytes memory encoded = readBytesField(cursor, min, max);
        if (!validUtf8(encoded)) {
            revert DecodeError("invalid utf-8");
        }
        return string(encoded);
    }

    /// Validates UTF-8 with the same scalar-value rules as Rust `str`: no overlong forms,
    /// surrogates, values above U+10FFFF, truncated sequences, or stray continuation bytes.
    function validUtf8(bytes memory encoded) private pure returns (bool) {
        uint256 i;
        while (i < encoded.length) {
            uint8 first = uint8(encoded[i]);
            if (first <= 0x7F) {
                ++i;
                continue;
            }
            if (first >= 0xC2 && first <= 0xDF) {
                if (i + 1 >= encoded.length || !continuation(encoded[i + 1])) return false;
                i += 2;
                continue;
            }
            if (first >= 0xE0 && first <= 0xEF) {
                if (i + 2 >= encoded.length || !continuation(encoded[i + 1]) || !continuation(encoded[i + 2])) {
                    return false;
                }
                uint8 second = uint8(encoded[i + 1]);
                if ((first == 0xE0 && second < 0xA0) || (first == 0xED && second > 0x9F)) return false;
                i += 3;
                continue;
            }
            if (first >= 0xF0 && first <= 0xF4) {
                if (
                    i + 3 >= encoded.length || !continuation(encoded[i + 1]) || !continuation(encoded[i + 2])
                        || !continuation(encoded[i + 3])
                ) return false;
                uint8 second = uint8(encoded[i + 1]);
                if ((first == 0xF0 && second < 0x90) || (first == 0xF4 && second > 0x8F)) return false;
                i += 4;
                continue;
            }
            return false;
        }
        return true;
    }

    function continuation(bytes1 character) private pure returns (bool) {
        uint8 value = uint8(character);
        return value >= 0x80 && value <= 0xBF;
    }

    function readPresence(Cursor memory cursor) private pure returns (bool present) {
        uint8 tag = readU8(cursor);
        if (tag == 0) {
            return false;
        }
        if (tag == 1) {
            return true;
        }
        revert DecodeError("presence tag");
    }
}
