//! Known-answer tests against vectors emitted by the Cairo contract.
//!
//! Fixture is `crates/discovery-core/tests/fixtures/cairo-reference-data.json` from
//! `starkware-libs/starknet-privacy`, generated by
//! `packages/privacy/src/tests/generate_reference_data.cairo`. Regenerate with:
//!
//! ```sh
//! cd starknet-privacy && snforge test generate_reference_hashes --include-ignored
//! ```
//!
//! These tests pin each derivation before use. A wrong preimage derives an unwritten storage
//! slot, and the note appears absent without an error.

use erebus_sdk::hashes;
use serde::Deserialize;
use starknet_types_core::felt::Felt;

#[derive(Deserialize)]
struct ReferenceData {
    inputs: Inputs,
    outputs: Outputs,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Inputs {
    sender: String,
    recipient: String,
    sender_private_key: String,
    recipient_public_key: String,
    channel_key: String,
    token: String,
    index: u64,
    salt: String,
    shared_x: String,
    amount: u64,
    user_addr: String,
    user_private_key: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Outputs {
    channel_key: String,
    channel_marker: String,
    subchannel_id: String,
    subchannel_marker: String,
    note_id: String,
    nullifier: String,
    enc_amount_hash: String,
    enc_token_hash: String,
    enc_private_key_hash: String,
    enc_channel_key_hash: String,
    enc_sender_addr_hash: String,
    enc_recipient_addr_hash: String,
    outgoing_channel_id: String,
}

fn felt(hex: &str) -> Felt {
    Felt::from_hex(hex).expect("fixture value is not a valid felt")
}

fn load() -> ReferenceData {
    let raw = include_str!("fixtures/cairo-reference-data.json");
    serde_json::from_str(raw).expect("fixture does not match the expected shape")
}

#[test]
fn channel_key_matches_cairo() {
    let d = load();
    assert_eq!(
        hashes::compute_channel_key(
            felt(&d.inputs.sender),
            felt(&d.inputs.sender_private_key),
            felt(&d.inputs.recipient),
            felt(&d.inputs.recipient_public_key),
        ),
        felt(&d.outputs.channel_key)
    );
}

#[test]
fn channel_marker_matches_cairo() {
    let d = load();
    assert_eq!(
        hashes::compute_channel_marker(
            felt(&d.inputs.channel_key),
            felt(&d.inputs.sender),
            felt(&d.inputs.recipient),
            felt(&d.inputs.recipient_public_key),
        ),
        felt(&d.outputs.channel_marker)
    );
}

#[test]
fn subchannel_id_matches_cairo() {
    let d = load();
    assert_eq!(
        hashes::compute_subchannel_id(felt(&d.inputs.channel_key), d.inputs.index),
        felt(&d.outputs.subchannel_id)
    );
}

#[test]
fn subchannel_marker_matches_cairo() {
    let d = load();
    assert_eq!(
        hashes::compute_subchannel_marker(
            felt(&d.inputs.channel_key),
            felt(&d.inputs.recipient),
            felt(&d.inputs.recipient_public_key),
            felt(&d.inputs.token),
        ),
        felt(&d.outputs.subchannel_marker)
    );
}

#[test]
fn note_id_matches_cairo() {
    let d = load();
    assert_eq!(
        hashes::compute_note_id(
            felt(&d.inputs.channel_key),
            felt(&d.inputs.token),
            d.inputs.index
        ),
        felt(&d.outputs.note_id)
    );
}

#[test]
fn nullifier_matches_cairo() {
    let d = load();
    assert_eq!(
        hashes::compute_nullifier(
            felt(&d.inputs.channel_key),
            felt(&d.inputs.token),
            d.inputs.index,
            felt(&d.inputs.sender_private_key),
        ),
        felt(&d.outputs.nullifier)
    );
}

#[test]
fn outgoing_channel_id_matches_cairo() {
    let d = load();
    assert_eq!(
        hashes::compute_outgoing_channel_id(
            felt(&d.inputs.sender),
            felt(&d.inputs.sender_private_key),
            d.inputs.index,
        ),
        felt(&d.outputs.outgoing_channel_id)
    );
}

/// The salt-type split the audit flagged: `u128` here, `Felt` in the two below.
/// If these ever pass with the types swapped, the port has drifted from the contract.
#[test]
fn enc_amount_hash_matches_cairo_with_u128_salt() {
    let d = load();
    let salt: u128 = u128::from_str_radix(d.inputs.salt.trim_start_matches("0x"), 16)
        .expect("salt fixture is not a u128");
    assert_eq!(
        hashes::compute_enc_amount_hash(
            felt(&d.inputs.channel_key),
            felt(&d.inputs.token),
            d.inputs.index,
            salt,
        ),
        felt(&d.outputs.enc_amount_hash)
    );
}

#[test]
fn enc_token_hash_matches_cairo_with_felt_salt() {
    let d = load();
    assert_eq!(
        hashes::compute_enc_token_hash(
            felt(&d.inputs.channel_key),
            d.inputs.index,
            felt(&d.inputs.salt),
        ),
        felt(&d.outputs.enc_token_hash)
    );
}

#[test]
fn enc_recipient_addr_hash_matches_cairo() {
    let d = load();
    assert_eq!(
        hashes::compute_enc_recipient_addr_hash(
            felt(&d.inputs.sender),
            felt(&d.inputs.sender_private_key),
            d.inputs.index,
            felt(&d.inputs.salt),
        ),
        felt(&d.outputs.enc_recipient_addr_hash)
    );
}

#[test]
fn ecdh_mask_hashes_match_cairo() {
    let d = load();
    let shared_x = felt(&d.inputs.shared_x);
    assert_eq!(
        hashes::compute_enc_channel_key_hash(shared_x),
        felt(&d.outputs.enc_channel_key_hash)
    );
    assert_eq!(
        hashes::compute_enc_sender_addr_hash(shared_x),
        felt(&d.outputs.enc_sender_addr_hash)
    );
    assert_eq!(
        hashes::compute_enc_private_key_hash(shared_x),
        felt(&d.outputs.enc_private_key_hash)
    );
}

/// Guards the fixture itself: if these drift, the vectors were regenerated against a
/// different contract build and every test above is comparing to the wrong thing.
#[test]
fn fixture_is_internally_consistent() {
    let d = load();
    assert_eq!(d.inputs.index, 5);
    assert_eq!(d.inputs.amount, 1000);
    assert_ne!(felt(&d.inputs.user_addr), Felt::ZERO);
    assert_ne!(felt(&d.inputs.user_private_key), Felt::ZERO);
}
